### PR TITLE
Chore/travis

### PR DESCRIPTION
**Pull request by fsmanuel**
Don't merge yet.

### CODE REVIEW

**Comment by fsmanuel** [comment]
@halo can you activate travis. It seems that the permissions are not sufficient for me to do that.
https://travis-ci.org/halo/bender

**Comment by halo** [comment]
Done

**Comment by fsmanuel** [comment]
Hmm can you try it here https://travis-ci.org/profile/halo again?

**Comment by halo** [comment]
Look at that, there was a switch not turned on :)

**Pull request merged**
